group: legalbench_mini_issue
group_alias: issue
task:
  - learned_hands_consumer_mini
  - learned_hands_divorce_mini
  - corporate_lobbying_mini
  - learned_hands_housing_mini
  - learned_hands_domestic_violence_mini
  - learned_hands_business_mini
  - learned_hands_benefits_mini
  - learned_hands_traffic_mini
  - learned_hands_torts_mini
  - learned_hands_employment_mini
  - learned_hands_estates_mini
  - learned_hands_crime_mini
  - learned_hands_immigration_mini
  - learned_hands_health_mini
  - learned_hands_education_mini
  - learned_hands_courts_mini
  - learned_hands_family_mini
