dataset_name: personal_jurisdiction
dataset_path: nguha/legalbench
doc_to_choice:
- 'Yes'
- 'No'
doc_to_target: '{{answer}}'
include: ../../prompt_templates/personal_jurisdiction/base_prompt.yaml
metric_list:
- aggregation: balanced_acc
  higher_is_better: true
  metric: balanced_acc
output_type: multiple_choice
task: personal_jurisdiction
test_split: test
training_split: train
