dataset_name: ucc_v_common_law
dataset_path: nguha/legalbench
doc_to_choice:
- UCC
- Common Law
doc_to_target: '{{answer}}'
group: legalbench_rule
group_alias: rule
include: ../../prompt_templates/ucc_v_common_law/base_prompt.yaml
metric_list:
- aggregation: balanced_acc
  higher_is_better: true
  metric: balanced_acc
output_type: multiple_choice
task: ucc_v_common_law
test_split: test
training_split: train
