dataset_name: maud_type_of_consideration
dataset_path: hoorangyee/legalbench_tiny
doc_to_target: '{{answer}}'
include: ../prompt_templates/maud_type_of_consideration/base_prompt.yaml
metric_list:
- aggregation: balanced_acc
  higher_is_better: true
  metric: balanced_acc
output_type: generate_until
task: maud_type_of_consideration_tiny_generative
test_split: test
training_split: train
