dataset_name: maud_application_of_buyer_consent_requirement_(negative_interim_covenant)
dataset_path: hoorangyee/legalbench_tiny
doc_to_target: '{{answer}}'
include: ../prompt_templates/maud_application_of_buyer_consent_requirement_(negative_interim_covenant)/base_prompt.yaml
metric_list:
- aggregation: balanced_acc
  higher_is_better: true
  metric: balanced_acc
output_type: generate_until
task: maud_application_of_buyer_consent_requirement_(negative_interim_covenant)_tiny_generative
test_split: test
training_split: train
filter_list:
- name: strict-match
  filter:
  - function: regex
    regex_pattern: '((?<=The answer is )(.*)(?=.)|(?<=answer is )(.*)(?=.)|(?<=The answer: )(.*)(?=.)|(?<=The final answer: )(.*)(?=.))'
  - function: take_first
