dataset_name: maud_pandemic_or_other_public_health_event__subject_to_disproportionate_impact_modifier
dataset_path: hoorangyee/legalbench_tiny
doc_to_target: '{{answer}}'
include: ../prompt_templates/maud_pandemic_or_other_public_health_event__subject_to_disproportionate_impact_modifier/base_prompt.yaml
metric_list:
- aggregation: balanced_acc
  higher_is_better: true
  metric: balanced_acc
output_type: generate_until
task: maud_pandemic_or_other_public_health_event__subject_to_disproportionate_impact_modifier_tiny_generative
test_split: test
training_split: train
