doc_to_text: "Determine whether the following statements are entailed under the statute.\n\
  \nStatute:     (v) $79,772, plus 39.6% of the excess over $250,000 if the taxable\
  \ income is over $250,000.\nDescription: Alice's taxable income for the year 2017\
  \ is $718791. Alice is not married, is not a surviving spouse, and is not a head\
  \ of household in 2017.\nStatement: Alice has to pay $265413 in taxes for the year\
  \ 2017 under section 1(c)(v).\nAnswer: Entailment\n\nStatute:         (A) whose\
  \ spouse died during either of the two years immediately preceding the taxable year,\
  \ and\nDescription: Alice and Bob got married on Feb 3rd, 1992. Alice died on July\
  \ 9th, 2014.\nStatement: Section 2(a)(1)(A) applies to Bob in 2015.\nAnswer: Entailment\n\
  \nStatute:     (iv) $31,172, plus 36% of the excess over $115,000 if the taxable\
  \ income is over $115,000 but not over $250,000;\nDescription: Alice's taxable income\
  \ for the year 2017 is $102268. In 2017, Alice is not married, is not a surviving\
  \ spouse, and is not a head of household.\nStatement: Alice has to pay $27225 in\
  \ taxes for the year 2017 under section 1(c)(iv).\nAnswer: Contradiction\n\nStatute:\
  \         (A) $300,000 in the case of a joint return or a surviving spouse (as defined\
  \ in section 2(a)),\nDescription: In 2016, Alice's income was $567192. Alice is\
  \ married for the year 2016 under section 7703. Alice does not file a joint return.\n\
  Statement: Section 68(b)(1)(A) applies to Alice for 2016.\nAnswer: Contradiction\n\
  \nStatute: {{statute}}\nDescription: {{description}}\nStatement: {{question}}\n\
  Answer: Let's think step by step."
