group: legalbench_tiny_interpretation
group_alias: interpretation
task:
- maud_general_economic_and_financial_conditions_subject_to_disproportionate_impact_modifier_tiny
- opp115_user_access,_edit_and_deletion_tiny
- maud_relational_language_(mae)_applies_to_tiny
- supply_chain_disclosure_disclosed_training_tiny
- contract_nli_explicit_identification_tiny
- maud_changes_in_gaap_or_other_accounting_principles__subject_to_disproportionate_impact_modifier_tiny
- maud_change_in_law__subject_to_disproportionate_impact_modifier_tiny
- cuad_most_favored_nation_tiny
- cuad_no-solicit_of_employees_tiny
- maud_cor_standard_(superior_offer)_tiny
- cuad_joint_ip_ownership_tiny
- cuad_cap_on_liability_tiny
- maud_accuracy_of_fundamental_target_rws_bringdown_standard_tiny
- opp115_policy_change_tiny
- maud_buyer_consent_requirement_(ordinary_course)_tiny
- privacy_policy_entailment_tiny
- cuad_revenue-profit_sharing_tiny
- supply_chain_disclosure_disclosed_certification_tiny
- contract_nli_limited_use_tiny
- cuad_effective_date_tiny
- cuad_non-transferable_license_tiny
- contract_nli_sharing_with_third-parties_tiny
- cuad_non-disparagement_tiny
- maud_type_of_consideration_tiny
- cuad_warranty_duration_tiny
- cuad_anti-assignment_tiny
- consumer_contracts_qa_tiny
- maud_knowledge_definition_tiny
- maud_initial_matching_rights_period_(cor)_tiny
- ssla_company_defendants_tiny
- maud_ordinary_course_efforts_standard_tiny
- privacy_policy_qa_tiny
- cuad_source_code_escrow_tiny
- cuad_exclusivity_tiny
- supply_chain_disclosure_best_practice_verification_tiny
- cuad_governing_law_tiny
- maud_cor_standard_(intervening_event)_tiny
- maud_liability_standard_for_no-shop_breach_by_target_non-do_representatives_tiny
- proa_tiny
- contract_nli_survival_of_obligations_tiny
- maud_additional_matching_rights_period_for_modifications_(cor)_tiny
- supply_chain_disclosure_best_practice_accountability_tiny
- maud_pandemic_or_other_public_health_event__subject_to_disproportionate_impact_modifier_tiny
- supply_chain_disclosure_disclosed_accountability_tiny
- opp115_first_party_collection_use_tiny
- contract_nli_inclusion_of_verbally_conveyed_information_tiny
- opp115_data_retention_tiny
- jcrew_blocker_tiny
- supply_chain_disclosure_best_practice_audits_tiny
- cuad_unlimited-all-you-can-eat-license_tiny
- cuad_affiliate_license-licensee_tiny
- maud_accuracy_of_target_capitalization_rw_(outstanding_shares)_bringdown_standard_answer_tiny
- maud_application_of_buyer_consent_requirement_(negative_interim_covenant)_tiny
- sara_numeric_tiny
- contract_nli_return_of_confidential_information_tiny
- cuad_no-solicit_of_customers_tiny
- maud_fiduciary_exception_board_determination_trigger_(no_shop)_tiny
- maud_initial_matching_rights_period_(ftr)_tiny
- maud_includes_consistent_with_past_practice_tiny
- maud_ability_to_consummate_concept_is_subject_to_mae_carveouts_tiny
- supply_chain_disclosure_best_practice_certification_tiny
- cuad_irrevocable_or_perpetual_license_tiny
- cuad_competitive_restriction_exception_tiny
- cuad_liquidated_damages_tiny
- legal_unfair_tos_tiny
- cuad_post-termination_services_tiny
- supply_chain_disclosure_best_practice_training_tiny
- ssla_individual_defendants_tiny
- cuad_expiration_date_tiny
- opp115_data_security_tiny
- maud_definition_includes_stock_deals_tiny
- cuad_affiliate_license-licensor_tiny
- contract_nli_permissible_acquirement_of_similar_information_tiny
- cuad_non-compete_tiny
- cuad_audit_rights_tiny
- contract_nli_confidentiality_of_agreement_tiny
- contract_nli_no_licensing_tiny
- maud_tail_period_length_tiny
- supply_chain_disclosure_disclosed_verification_tiny
- cuad_volume_restriction_tiny
- cuad_change_of_control_tiny
- cuad_license_grant_tiny
- contract_nli_sharing_with_employees_tiny
- maud_fiduciary_exception__board_determination_standard_tiny
- cuad_renewal_term_tiny
- supply_chain_disclosure_disclosed_audits_tiny
- cuad_tinymum_commitment_tiny
- opp115_international_and_specific_audiences_tiny
- opp115_user_choice_control_tiny
- maud_fls_(mae)_standard_tiny
- cuad_termination_for_convenience_tiny
- insurance_policy_interpretation_tiny
- cuad_covenant_not_to_sue_tiny
- contract_qa_tiny
- opp115_do_not_track_tiny
- cuad_insurance_tiny
- maud_cor_permitted_in_response_to_intervening_event_tiny
- contract_nli_permissible_post-agreement_possession_tiny
- maud_financial_point_of_view_is_the_sole_consideration_tiny
- maud_definition_includes_asset_deals_tiny
- cuad_uncapped_liability_tiny
- cuad_third_party_beneficiary_tiny
- maud_specific_performance_tiny
- maud_accuracy_of_target_general_rw_bringdown_timing_answer_tiny
- maud_pandemic_or_other_public_health_event_specific_reference_to_pandemic-related_governmental_responses_or_measures_tiny
- maud_definition_contains_knowledge_requirement_-_answer_tiny
- maud_cor_permitted_with_board_fiduciary_determination_only_tiny
- contract_nli_notice_on_compelled_disclosure_tiny
- cuad_ip_ownership_assignment_tiny
- opp115_third_party_sharing_collection_tiny
- cuad_rofr-rofo-rofn_tiny
- maud_intervening_event_-_required_to_occur_after_signing_-_answer_tiny
- cuad_price_restrictions_tiny
- cuad_notice_period_to_terminate_renewal_tiny
- sara_entailment_tiny
