dataset_name: maud_additional_matching_rights_period_for_modifications_(cor)
dataset_path: hoorangyee/legalbench_tiny
doc_to_choice:
- A
- B
- C
- D
- E
- F
- G
doc_to_target: '{{answer}}'
include: ../prompt_templates/maud_additional_matching_rights_period_for_modifications_(cor)/base_prompt.yaml
metric_list:
- aggregation: balanced_acc
  higher_is_better: true
  metric: balanced_acc
output_type: multiple_choice
task: maud_additional_matching_rights_period_for_modifications_(cor)_tiny
test_split: test
training_split: train
