dataset_name: diversity_3
dataset_path: hoorangyee/legalbench_tiny
doc_to_target: '{{answer}}'
include: ../../prompt_templates/diversity_3/base_prompt.yaml
metric_list:
- aggregation: balanced_acc
  higher_is_better: true
  metric: balanced_acc
output_type: generate_until
task: diversity_3_tiny_generative
test_split: test
training_split: train
