dataset_name: contract_nli_explicit_identification
dataset_path: hoorangyee/legalbench_mini
doc_to_target: '{{answer}}'
include: ../prompt_templates/contract_nli_explicit_identification/base_prompt.yaml
metric_list:
- aggregation: balanced_acc
  higher_is_better: true
  metric: balanced_acc
output_type: generate_until
task: contract_nli_explicit_identification_mini_generative
test_split: test
training_split: train
