dataset_name: cuad_irrevocable_or_perpetual_license
dataset_path: hoorangyee/legalbench_mini
doc_to_choice:
- 'Yes'
- 'No'
doc_to_target: '{{answer}}'
include: ../prompt_templates/cuad_irrevocable_or_perpetual_license/base_prompt.yaml
metric_list:
- aggregation: balanced_acc
  higher_is_better: true
  metric: balanced_acc
output_type: multiple_choice
task: cuad_irrevocable_or_perpetual_license_mini_generative
test_split: test
training_split: train
