dataset_name: maud_fiduciary_exception__board_determination_standard
dataset_path: hoorangyee/legalbench_mini
doc_to_choice:
- A
- B
- C
- D
- E
- F
- G
- H
- I
doc_to_target: '{{answer}}'
include: ../prompt_templates/maud_fiduciary_exception__board_determination_standard/base_prompt.yaml
metric_list:
- aggregation: balanced_acc
  higher_is_better: true
  metric: balanced_acc
output_type: multiple_choice
task: maud_fiduciary_exception__board_determination_standard_mini_generative
test_split: test
training_split: train
