dataset_name: maud_general_economic_and_financial_conditions_subject_to_disproportionate_impact_modifier
dataset_path: hoorangyee/legalbench_mini
doc_to_target: '{{answer}}'
include: ../prompt_templates/maud_general_economic_and_financial_conditions_subject_to_disproportionate_impact_modifier/base_prompt.yaml
metric_list:
- aggregation: balanced_acc
  higher_is_better: true
  metric: balanced_acc
output_type: generate_until
task: maud_general_economic_and_financial_conditions_subject_to_disproportionate_impact_modifier_mini_generative
test_split: test
training_split: train
