dataset_name: maud_accuracy_of_target_general_rw_bringdown_timing_answer
dataset_path: hoorangyee/legalbench_mini
doc_to_target: '{{answer}}'
include: ../prompt_templates/maud_accuracy_of_target_general_rw_bringdown_timing_answer/base_prompt.yaml
metric_list:
- aggregation: balanced_acc
  higher_is_better: true
  metric: balanced_acc
output_type: generate_until
task: maud_accuracy_of_target_general_rw_bringdown_timing_answer_mini_generative
test_split: test
training_split: train
