dataset_name: maud_includes_consistent_with_past_practice
dataset_path: hoorangyee/legalbench_mini
doc_to_target: '{{answer}}'
include: ../prompt_templates/maud_includes_consistent_with_past_practice/base_prompt.yaml
metric_list:
- aggregation: balanced_acc
  higher_is_better: true
  metric: balanced_acc
output_type: generate_until
task: maud_includes_consistent_with_past_practice_mini_generative
test_split: test
training_split: train
