dataset_name: maud_fls_(mae)_standard
dataset_path: hoorangyee/legalbench_mini
doc_to_choice:
- A
- B
- C
- D
- E
doc_to_target: '{{answer}}'
include: ../prompt_templates/maud_fls_(mae)_standard/base_prompt.yaml
metric_list:
- aggregation: balanced_acc
  higher_is_better: true
  metric: balanced_acc
output_type: multiple_choice
task: maud_fls_(mae)_standard_mini_generative
test_split: test
training_split: train
