dataset_name: maud_relational_language_(mae)_applies_to
dataset_path: hoorangyee/legalbench_mini
doc_to_target: '{{answer}}'
include: ../prompt_templates/maud_relational_language_(mae)_applies_to/base_prompt.yaml
metric_list:
- aggregation: balanced_acc
  higher_is_better: true
  metric: balanced_acc
output_type: generate_until
task: maud_relational_language_(mae)_applies_to_mini_generative
test_split: test
training_split: train
