dataset_name: opp115_international_and_specific_audiences
dataset_path: hoorangyee/legalbench_mini
doc_to_target: '{{answer}}'
include: ../prompt_templates/opp115_international_and_specific_audiences/base_prompt.yaml
metric_list:
- aggregation: balanced_acc
  higher_is_better: true
  metric: balanced_acc
output_type: generate_until
task: opp115_international_and_specific_audiences_mini_generative
test_split: test
training_split: train
