dataset_name: opp115_first_party_collection_use
dataset_path: hoorangyee/legalbench_mini
doc_to_target: '{{answer}}'
include: ../prompt_templates/opp115_first_party_collection_use/base_prompt.yaml
metric_list:
- aggregation: balanced_acc
  higher_is_better: true
  metric: balanced_acc
output_type: generate_until
task: opp115_first_party_collection_use_mini_generative
test_split: test
training_split: train
