dataset_name: privacy_policy_entailment
dataset_path: hoorangyee/legalbench_mini
doc_to_choice:
- Correct
- Incorrect
doc_to_target: '{{answer}}'
include: ../prompt_templates/privacy_policy_entailment/base_prompt.yaml
metric_list:
- aggregation: balanced_acc
  higher_is_better: true
  metric: balanced_acc
output_type: multiple_choice
task: privacy_policy_entailment_mini_generative
test_split: test
training_split: train
