dataset_name: learned_hands_employment
dataset_path: nguha/legalbench
doc_to_choice:
- 'Yes'
- 'No'
doc_to_target: '{{answer}}'
group: legalbench_issue
group_alias: issue
include: ../prompt_templates/learned_hands_employment/base_prompt.yaml
metric_list:
- aggregation: balanced_acc
  higher_is_better: true
  metric: balanced_acc
output_type: multiple_choice
task: learned_hands_employment
test_split: test
training_split: train
