group: legalbench_interpretaion
group_alias: interpretation
task:
  - maud_general_economic_and_financial_conditions_subject_to_disproportionate_impact_modifier
  - opp115_user_access,_edit_and_deletion
  - maud_relational_language_(mae)_applies_to
  - supply_chain_disclosure_disclosed_training
  - contract_nli_explicit_identification
  - maud_changes_in_gaap_or_other_accounting_principles__subject_to_disproportionate_impact_modifier
  - maud_change_in_law__subject_to_disproportionate_impact_modifier
  - cuad_most_favored_nation
  - cuad_no-solicit_of_employees
  - maud_cor_standard_(superior_offer)
  - cuad_joint_ip_ownership
  - cuad_cap_on_liability
  - maud_accuracy_of_fundamental_target_rws_bringdown_standard
  - opp115_policy_change
  - maud_buyer_consent_requirement_(ordinary_course)
  - privacy_policy_entailment
  - cuad_revenue-profit_sharing
  - supply_chain_disclosure_disclosed_certification
  - contract_nli_limited_use
  - cuad_effective_date
  - cuad_non-transferable_license
  - contract_nli_sharing_with_third-parties
  - cuad_non-disparagement
  - maud_type_of_consideration
  - cuad_warranty_duration
  - cuad_anti-assignment
  - consumer_contracts_qa
  - ssla_plaintiff
  - maud_knowledge_definition
  - maud_initial_matching_rights_period_(cor)
  - ssla_company_defendants
  - maud_ordinary_course_efforts_standard
  - privacy_policy_qa
  - cuad_source_code_escrow
  - cuad_exclusivity
  - supply_chain_disclosure_best_practice_verification
  - cuad_governing_law
  - maud_cor_standard_(intervening_event)
  - maud_liability_standard_for_no-shop_breach_by_target_non-do_representatives
  - proa
  - contract_nli_survival_of_obligations
  - maud_additional_matching_rights_period_for_modifications_(cor)
  - supply_chain_disclosure_best_practice_accountability
  - maud_pandemic_or_other_public_health_event__subject_to_disproportionate_impact_modifier
  - supply_chain_disclosure_disclosed_accountability
  - opp115_first_party_collection_use
  - contract_nli_inclusion_of_verbally_conveyed_information
  - opp115_data_retention
  - jcrew_blocker
  - supply_chain_disclosure_best_practice_audits
  - cuad_unlimited-all-you-can-eat-license
  - cuad_affiliate_license-licensee
  - maud_accuracy_of_target_capitalization_rw_(outstanding_shares)_bringdown_standard_answer
  - maud_application_of_buyer_consent_requirement_(negative_interim_covenant)
  - sara_numeric
  - contract_nli_return_of_confidential_information
  - cuad_no-solicit_of_customers
  - maud_fiduciary_exception_board_determination_trigger_(no_shop)
  - maud_initial_matching_rights_period_(ftr)
  - maud_includes_consistent_with_past_practice
  - maud_ability_to_consummate_concept_is_subject_to_mae_carveouts
  - supply_chain_disclosure_best_practice_certification
  - cuad_irrevocable_or_perpetual_license
  - cuad_competitive_restriction_exception
  - cuad_liquidated_damages
  - legal_unfair_tos
  - cuad_post-termination_services
  - supply_chain_disclosure_best_practice_training
  - ssla_individual_defendants
  - cuad_expiration_date
  - opp115_data_security
  - maud_definition_includes_stock_deals
  - cuad_affiliate_license-licensor
  - contract_nli_permissible_acquirement_of_similar_information
  - cuad_non-compete
  - cuad_audit_rights
  - contract_nli_confidentiality_of_agreement
  - contract_nli_no_licensing
  - maud_tail_period_length
  - supply_chain_disclosure_disclosed_verification
  - cuad_volume_restriction
  - cuad_change_of_control
  - cuad_license_grant
  - contract_nli_sharing_with_employees
  - maud_fiduciary_exception__board_determination_standard
  - cuad_renewal_term
  - supply_chain_disclosure_disclosed_audits
  - cuad_minimum_commitment
  - opp115_international_and_specific_audiences
  - opp115_user_choice_control
  - maud_fls_(mae)_standard
  - cuad_termination_for_convenience
  - insurance_policy_interpretation
  - cuad_covenant_not_to_sue
  - contract_qa
  - opp115_do_not_track
  - cuad_insurance
  - maud_cor_permitted_in_response_to_intervening_event
  - contract_nli_permissible_post-agreement_possession
  - maud_financial_point_of_view_is_the_sole_consideration
  - maud_definition_includes_asset_deals
  - cuad_uncapped_liability
  - cuad_third_party_beneficiary
  - maud_specific_performance
  - maud_accuracy_of_target_general_rw_bringdown_timing_answer
  - maud_pandemic_or_other_public_health_event_specific_reference_to_pandemic-related_governmental_responses_or_measures
  - maud_definition_contains_knowledge_requirement_-_answer
  - maud_cor_permitted_with_board_fiduciary_determination_only
  - contract_nli_notice_on_compelled_disclosure
  - cuad_ip_ownership_assignment
  - opp115_third_party_sharing_collection
  - cuad_rofr-rofo-rofn
  - maud_intervening_event_-_required_to_occur_after_signing_-_answer
  - cuad_price_restrictions
  - cuad_notice_period_to_terminate_renewal
  - sara_entailment
