dataset_name: contract_nli_permissible_copy
dataset_path: nguha/legalbench
doc_to_choice:
- 'Yes'
- 'No'
doc_to_target: '{{answer}}'
include: ../prompt_templates/contract_nli_permissible_copy/base_prompt.yaml
metric_list:
- aggregation: balanced_acc
  higher_is_better: true
  metric: balanced_acc
output_type: multiple_choice
task: contract_nli_permissible_copy
test_split: test
training_split: train