dataset_name: cuad_unlimited-all-you-can-eat-license
dataset_path: nguha/legalbench
doc_to_choice:
- 'Yes'
- 'No'
doc_to_target: '{{answer}}'
include: ../prompt_templates/cuad_unlimited-all-you-can-eat-license/base_prompt.yaml
metric_list:
- aggregation: balanced_acc
  higher_is_better: true
  metric: balanced_acc
output_type: multiple_choice
task: cuad_unlimited-all-you-can-eat-license
test_split: test
training_split: train
