dataset_name: maud_change_in_law__subject_to_disproportionate_impact_modifier
dataset_path: nguha/legalbench
doc_to_choice:
- A
- B
doc_to_target: '{{answer}}'
group: legalbench_interpretation
group_alias: interpretation
include: ../prompt_templates/maud_change_in_law__subject_to_disproportionate_impact_modifier/base_prompt.yaml
metric_list:
- aggregation: balanced_acc
  higher_is_better: true
  metric: balanced_acc
output_type: multiple_choice
task: maud_change_in_law__subject_to_disproportionate_impact_modifier
test_split: test
training_split: train
