dataset_name: maud_accuracy_of_target_general_rw_bringdown_timing_answer
dataset_path: nguha/legalbench
doc_to_choice:
- A
- B
doc_to_target: '{{answer}}'
group: legalbench_interpretation
group_alias: interpretation
include: ../prompt_templates/maud_accuracy_of_target_general_rw_bringdown_timing_answer/base_prompt.yaml
metric_list:
- aggregation: balanced_acc
  higher_is_better: true
  metric: balanced_acc
output_type: multiple_choice
task: maud_accuracy_of_target_general_rw_bringdown_timing_answer
test_split: test
training_split: train
