dataset_name: ssla_company_defendants
dataset_path: nguha/legalbench
doc_to_target: '{{answer}}'
include: ../prompt_templates/ssla_company_defendants/base_prompt.yaml
metric_list:
- aggregation: ssla_f1
  higher_is_better: true
  metric: ssla_f1
output_type: generate_until
task: ssla_company_defendants
test_split: test
training_split: train
