dataset_name: citation_prediction_open
dataset_path: nguha/legalbench
doc_to_target: '{{answer}}'
group: legalbench_rule
group_alias: rule
include: ../../prompt_templates/citation_prediction_open/base_prompt.yaml
metric_list:
- aggregation: citation_acc
  higher_is_better: true
  metric: citation_acc
output_type: generate_until
task: citation_prediction_open
test_split: test
training_split: train
