dataset_name: scalr
dataset_path: hoorangyee/legalbench_mini
doc_to_target: '{{answer}}'
include: ../prompt_templates/scalr/base_prompt.yaml
metric_list:
- aggregation: balanced_acc
  higher_is_better: true
  metric: balanced_acc
output_type: generate_until
task: scalr_mini_generative
test_split: test
