task: biglawbench
dataset_path: hoorangyee/biglawbench_samples
dataset_name: default
output_type: generate_until
generation_kwargs:
  until:
    - "</s>"
judge_generation_kwargs:
  until:
    - "</s>"
test_split: train
doc_to_text: Prompt
doc_to_target: ""
doc_to_rubric: Rubric
metric_list:
  - metric: LLM-Eval
    aggregation: mean
    higher_is_better: true
    max_score: 10