dataset_name: scalr
dataset_path: hoorangyee/legalbench_tiny
doc_to_choice:
- '0'
- '1'
- '2'
- '3'
- '4'
doc_to_target: '{{answer}}'
include: ../prompt_templates/scalr/base_prompt.yaml
metric_list:
- aggregation: balanced_acc
  higher_is_better: true
  metric: balanced_acc
output_type: multiple_choice
task: scalr_tiny
test_split: test
