dataset_name: legal_reasoning_causality
dataset_path: hoorangyee/legalbench_tiny
doc_to_target: '{{answer}}'
include: ../prompt_templates/legal_reasoning_causality/base_prompt.yaml
metric_list:
- aggregation: balanced_acc
  higher_is_better: true
  metric: balanced_acc
output_type: generate_until
task: legal_reasoning_causality_tiny_generative
test_split: test
training_split: train
