dataset_name: overruling
dataset_path: hoorangyee/legalbench_tiny
doc_to_target: '{{answer}}'
include: ../prompt_templates/overruling/base_prompt.yaml
metric_list:
- aggregation: balanced_acc
  higher_is_better: true
  metric: balanced_acc
output_type: generate_until
task: overruling_tiny_generative
test_split: test
training_split: train
