dataset_name: abercrombie
dataset_path: hoorangyee/legalbench_mini
doc_to_query: text
doc_to_target: '{{answer}}'
include: ../../prompt_templates/abercrombie/base_prompt.yaml
metric_list:
- aggregation: balanced_acc
  higher_is_better: true
  metric: balanced_acc
output_type: generate_until
task: abercrombie_mini_generative
test_split: test
training_split: train
