dataset_name: ucc_v_common_law
dataset_path: hoorangyee/legalbench_mini
doc_to_target: '{{answer}}'
include: ../../prompt_templates/ucc_v_common_law/base_prompt.yaml
metric_list:
- aggregation: balanced_acc
  higher_is_better: true
  metric: balanced_acc
output_type: generate_until
task: ucc_v_common_law_mini_generative
test_split: test
training_split: train
