dataset_name: contract_qa
dataset_path: hoorangyee/legalbench_mini
doc_to_choice:
- 'Yes'
- 'No'
doc_to_target: '{{answer}}'
include: ../prompt_templates/contract_qa/base_prompt.yaml
metric_list:
- aggregation: balanced_acc
  higher_is_better: true
  metric: balanced_acc
output_type: multiple_choice
task: contract_qa_mini
test_split: test
training_split: train
