dataset_name: maud_pandemic_or_other_public_health_event_specific_reference_to_pandemic-related_governmental_responses_or_measures
dataset_path: hoorangyee/legalbench_mini
doc_to_choice:
- A
- B
doc_to_target: '{{answer}}'
include: ../prompt_templates/maud_pandemic_or_other_public_health_event_specific_reference_to_pandemic-related_governmental_responses_or_measures/base_prompt.yaml
metric_list:
- aggregation: balanced_acc
  higher_is_better: true
  metric: balanced_acc
output_type: multiple_choice
task: maud_pandemic_or_other_public_health_event_specific_reference_to_pandemic-related_governmental_responses_or_measures_mini
test_split: test
training_split: train
