task: lawbench_3_4_zeroshot
dataset_path: doolayer/LawBench
dataset_name: 3-4
output_type: generate_until
test_split: test
generation_kwargs:
  until:
    - "</s>"
  max_gen_toks: 128
doc_to_text: !function utils_lawbench.doc_to_text
doc_to_target: !function utils_lawbench_3_4.doc_to_target_3_4
metric_list:
  - metric: !function utils_lawbench_3_4.lawbench_3_4_log_distance
    aggregation: mean
    higher_is_better: true