dataset_name: corporate_lobbying
dataset_path: hoorangyee/legalbench_mini
doc_to_target: '{{answer}}'
include: ../prompt_templates/corporate_lobbying/base_prompt.yaml
metric_list:
- aggregation: balanced_acc
  higher_is_better: true
  metric: balanced_acc
output_type: generate_until
task: corporate_lobbying_mini_generative
test_split: test
training_split: train
