dataset_name: definition_extraction
dataset_path: nguha/legalbench
doc_to_target: '{{answer}}'
include: ../prompt_templates/definition_extraction/base_prompt.yaml
metric_list:
- aggregation: definition_extraction_acc
  higher_is_better: true
  metric: definition_extraction_acc
output_type: generate_until
task: definition_extraction
test_split: test
training_split: train
