dataset_name: textualism_tool_dictionaries
dataset_path: nguha/legalbench
doc_to_choice:
- 'Yes'
- 'No'
doc_to_target: '{{answer}}'
group: legalbench_rhetorical_understanding
group_alias: rhetorical_understanding
include: ../prompt_templates/textualism_tool_dictionaries/base_prompt.yaml
metric_list:
- aggregation: balanced_acc
  higher_is_better: true
  metric: balanced_acc
output_type: multiple_choice
task: textualism_tool_dictionaries
test_split: test
training_split: train
